import type { Metadata } from "next";

import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import Provider from "@/components/Provider";
import 'react-toastify/dist/ReactToastify.css';
import "@uploadthing/react/styles.css";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TechStack",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Navbar />
          {children}
        </Provider>

        <ToastContainer />

      </body>

    </html>
  );
}
