import type { Metadata } from "next";
import { Inter } from "next/font/google";

import 'react-toastify/dist/ReactToastify.css';
import "./globals.css";
import Navbar from "@/components/Navbar";
import { getUser } from "@/lib/actions";
import { getServerSession } from "next-auth";
import { ToastContainer } from "react-toastify";
import { authOptions } from "@/lib/auth";
import Provider from "@/components/Provider";
import "@uploadthing/react/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Navbar/>
              {children}
        </Provider>

         <ToastContainer  />
    
      </body>
   
    </html>
  );
}
